service: product-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: eu-west-1

  apiGateway:
    minimumCompressionSize: 1024

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    PG_HOST: lesson-4.cxhfwgzvdjjg.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: products_service
    PG_USERNAME: postgres
    PG_PASSWORD: qwerty123


plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  getProducts:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: products
          cors: true

  getProduct:
    handler: handler.getProductById
    events:
      - http:
          method: get
          path: products/{productId}
          cors: true
