service: import-service

frameworkVersion: '2'

custom:
  bucketName: my-shop-app-files
  catalogItemsQueue: catalogItemsQueue

  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: eu-west-1

  apiGateway:
    minimumCompressionSize: 1024

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    BUCKET_NAME: ${self:custom.bucketName}
    SQS_URL:
      Ref: SQSQueue

  iamRoleStatements:
    - Effect: Allow
      Action: sqs:*
      Resource:
        - Fn::GetAtt:
          - SQSQueue
          - Arn

    - Effect: Allow
      Action: s3:*
      Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.catalogItemsQueue}
